---
name: Deploy to launchpad.net

on:
  push:
    tags:
      - v*.*.*-reddit*

jobs:
  build:
    name: Packaging software
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "$GITHUB_ENV"

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Trust key
        run: |
          gpg --no-tty --command-fd 0 --edit-key ${{ secrets.GPG_KEY_ID }} <<EOTRUST
          trust
          5
          y
          quit
          EOTRUST

      - name: List keys
        run: gpg -K

      - name: Run install commands
        run: sudo apt-get install -y dput devscripts debhelper moreutils help2man

      - name: Creating version
        run: |
          cd "$GITHUB_WORKSPACE"

          # remove v prefix from version
          DEB_VERSION="${RELEASE_VERSION#v}"
          # replace - with ~ in DEB_VERSION
          DEB_VERSION="${DEB_VERSION/-/\~}"

          echo -e "$DEB_VERSION" > share/github-backup-utils/version
          echo "DEB_VERSION=\"${DEB_VERSION}\"" >> $GITHUB_ENV
          
          cat > new_change << EOF
          github-backup-utils (${DEB_VERSION}) UNRELEASED; urgency=medium
            * built in CI
          
           -- github-actions <github@github.com>  $(date +'%a, %d %b %Y %T %z')
           
          EOF
          
          # prepend the new stuff above to the changelog
          cat new_change | cat - debian/changelog > /tmp/new_changelog && mv /tmp/new_changelog debian/changelog

          cat debian/changelog

      - name: Building Github Backup Utils
        run: |
          cd "$GITHUB_WORKSPACE"

          make dist

          # this makes the .changes file for the ppa upload
          debuild -S -sa -v${DEB_VERSION}

          ls -lha

      - name: Creating PPA configuration
        run: |
          echo "[reddit-ppa]" >> $HOME/.dput.cf
          echo "fqdn = ppa.launchpad.net" >> $HOME/.dput.cf
          echo "method = ftp" >> $HOME/.dput.cf
          echo "incoming = ${{ secrets.PPA_INCOMING }}" >> $HOME/.dput.cf
          echo "login = anonymous" >> $HOME/.dput.cf
          echo "allow_unsigned_uploads = 0" >> $HOME/.dput.cf

      - name: Publishing to PPA
        run: |
          cd $GITHUB_WORKSPACE
          ls -lha
          # dput reddit-ppa ../automysqlbackup_$(echo $GITHUB_REF | grep -oP "([0-9].*)" )_source.changes
